name: Release caddy binaries

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build
        run: |
          go mod download
          make

      - name: Upload caddy binaries to release artifaces
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
