name: Test caddy build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build and validate
        run: |
          # build
          echo "::group::Build binaries"
          go mod download
          make
          echo "::endgroup::"
          # validate
          echo "::group::Validate Caddyfiles"
          bash caddy-validate.sh
          echo "::endgroup::"
